name: Build and Push Docker

on:
  push:
    branches: [ yandex ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
    run:
      docker build . --file Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/delivery-service:latest
    - name: Login to YC Registry
      uses: docker/login-action@v3.0.0
      with:
        registry: cr.yandex
        username: json_key
        password: ${{ secrets.YC_KEYS }}

    - name: Push tag to YC Registry
      run: 
        docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/deliveryservice:latest 
