name: Build and Push Docker

on:
  push:
    branches: [ docker_hub_ci_cd ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Access secret
      run: echo "ENV_POSTGRES_APPEALS_URL=${{ secrets.ENV_POSTGRES_APPEALS_URL }}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/appeals:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/appeals:latest